<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerP3ml0op\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerP3ml0op/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerP3ml0op.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerP3ml0op\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerP3ml0op\appProdProjectContainer(array(
    'container.build_hash' => 'P3ml0op',
    'container.build_id' => '2b66f727',
    'container.build_time' => 1515935929,
));
