<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDstjklf\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDstjklf/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerDstjklf.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerDstjklf\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerDstjklf\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Dstjklf',
    'container.build_id' => 'a668c14b',
    'container.build_time' => 1515935262,
));
